name: kingdeal_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.3

dependencies:
  args: ^2.3.0
  html: ^0.15.3
  http: ^1.0.0
  neat_periodic_task: ^2.0.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
